### ISSUE TITLE
Mobile Meta

### ISSUE THREAD

**Issue by Mikeysax** [LampshadeWarrior/Squirty#1]
On mobile things don't look as good as they could be.

One thing you could look into is to add the "mobile meta tag" to your app, so the responsive effect of Bootstrap actually shows up on Mobile.

Let me know in the comments once you figured that step out :)

**Comment by LampshadeWarrior** [comment]
Hey @Mikeysax I just added the meta tag.

**Comment by Mikeysax** [comment]
:+1:
